

name: 'sumup'
version: '1.0.0'
config-version: 2
require-dbt-version: ">=1.3.0"

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"


models:
  sumup:    
    staging:
      materialized: view
      +schema: staging

    intermediary:
      materialized: table
      +schema: intermediary
    summary:
      materialized: table
      +schema: summary
    reports:
      materialized: table
      +schema: reporting