name: DBT Cloud CI
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  autoscaling:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    env:
      DBT_CLOUD_SERVICE_TOKEN: ${{ secrets.DBT_CLOUD_SERVICE_TOKEN }}
      DBT_CLOUD_ACCOUNT_ID: ${{ secrets.DBT_CLOUD_ACCOUNT_ID }}
      JOB_ID: ${{ secrets.DBT_CLOUD_JOB_ID }}
      PULL_REQUEST_ID: ${{ github.event.number }}
      GIT_SHA: ${{ github.event.pull_request.head.sha }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"

      - name: Trigger DBT CI Job
        run: |
          pip install dbtc==0.3.3
      
          run=$(dbtc trigger-autoscaling-ci-job \
            --job-id=$JOB_ID \
            --payload='{"cause": "DBT Slim CI!","git_sha":"'"$GIT_SHA"'","schema_override":"'""dbt_cicd""'","github_pull_request_id":'"$PULL_REQUEST_ID"'}' \
            --no-should-poll)
